### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by shchypylov** [ayoubdev/atom-formatter-jsbeautify#7]
Hi
I have installed all of packages, but got this

> BeautifyError: .jsbeautifyrc not found
> Details: Error: ENOENT: no such file or directory, open '/Users/Nikulio/Documents/Projects/react_docs/.jsbeautifyrc'
> Next behavior: Beautify with default configurations

**Comment by gamijin0** [comment]
the problem happens to me in the same way every time I  use this plugin , but I can still use it correctly to format my code

**Comment by Thecave3** [comment]
Well, any update about that?
